### ISSUE TITLE
Keep Mass function non functional and Props lose mass each time they spawn

### ISSUE THREAD

**Issue by Dakota0001** [DaDamRival/proper_clipping#24] opened 2021-05-12 06:02 UTC
Whether or not I have keep mass checked the prop loses mass after physclipping, also if I copy the prop with AD2 and paste it then it loses an amount of weight that seems proportional to the size of the clip, if I copy and paste the last copy then this process happens again losing more weight, repeats as many times as duped and respawned. 

It is currently causing lots of inconsistency issues with players trying to build contraptions as their weights keep changing whenever they spawn in their vehicles. Ideal settings would be just doing the required physical clips but otherwise not messing with weights at all and just letting players set them.

**Comment by Sevii77** [comment] 2021-05-31 10:38
As with #23 I'm unable to reproduce this.  Does this also happen without any other addons?

**Comment by Dakota0001** [comment] 2021-05-31 19:36
After further research and testing, we've found it seems to be some sort of compatibility issue with the addon ACF. Though even without ACF there's apparently an issue with physicize duplicating constraints even without other addons present.

Here is ACF https://github.com/Stooberton/ACF-3

I've notified the developers of ACF about this too and they will be attempting to figure out what could be the compatibility issue going on here.

**Comment by Sevii77** [comment] 2021-06-01 02:24
I am unable to reproduce the constraint duplication, can a step-by-step guide, or dupe file be provided?

**Comment by Dakota0001** [comment] 2021-06-01 10:38
Reproduction of constraint duplication is as follows:
>spawn 2 props
>visclip them (might require 2 clips)
>rope them together
>physicize the clips
>duplicate with AD2
>spawn

This results in duplicating the constraint, copying the copy and spawning it again doubles the constraints again, and so on.

**Comment by Sevii77** [comment] 2021-06-01 16:38
Fixed in 31abf4e

**Comment by Sevii77** [comment] 2021-06-28 20:51
Mass issue should be fixed in https://github.com/Stooberton/ACF-3/commit/91e6986edba38de55640b26e963d95b0d91c81b9

**Closed as completed by Sevii77** 2021-06-28 20:51 UTC
